### ISSUE TITLE
[REQ] Switch graphics next login

### ISSUE THREAD

**Issue by cirelli94** [beidl/prime-indicator#26]
Why don't add, bottom "Quick switch graphics" line, an option to switch graphics next login?

To me happens that I play with videogames, than I know I'll not need to use nvidia card at the next boot....

**Comment by andrebrait** [comment]
Hey there! I have been working on a fork lately. We've just reached version 1.0.0!

Submit your feature request to my repository so we can discuss and maybe implement it!

https://github.com/andrebrait/prime-indicator
