### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by jasmines** [beidl/prime-indicator#28]
PPAs from Webupd8 have not been updated for a year.
No one replies to requests.
WTF?

**Comment by fredldotme** [comment]
The Webupd8 repos ship, though I appreciate the packaging effort, inofficial packages and shouldn't be treated as an official way of distribution.
Also, with the way GNOME Shell is moving away from AppIndicators, there's little reason for me to continue maintaining the project when others use NVIDIA hardware on a daily basis.

You can check out newer, maintained forks here:
https://github.com/beidl/prime-indicator/network

**Comment by jasmines** [comment]
What can a KDE user do to have the same indicator running and
      regularly updated?
    
    
    Il 08/07/2018 13:33, Alfred E. Neumayer
      ha scritto:
    
    
      The Webupd8 repos ship, though I appreciate the packaging
        effort, inofficial packages and shouldn't be treated as an
        official way of distribution.
        Also, with the way GNOME Shell is moving away from
        AppIndicators, there's little reason for me to continue
        maintaining the project when others use NVIDIA hardware on a
        daily basis.
      You can check out newer, maintained forks here:
        https://github.com/beidl/prime-indicator/network
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/beidl/prime-indicator","title":"beidl/prime-indicator","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/beidl/prime-indicator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@beidl in #28: The Webupd8 repos ship, though I appreciate the packaging effort, inofficial packages and shouldn't be treated as an official way of distribution.\r\nAlso, with the way GNOME Shell is moving away from AppIndicators, there's little reason for me to continue maintaining the project when others use NVIDIA hardware on a daily basis.\r\n\r\nYou can check out newer, maintained forks here:\r\nhttps://github.com/beidl/prime-indicator/network"}],"action":{"name":"View Issue","url":"https://github.com/beidl/prime-indicator/issues/28#issuecomment-403281341"}}}
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/beidl/prime-indicator/issues/28#issuecomment-403281341",
"url": "https://github.com/beidl/prime-indicator/issues/28#issuecomment-403281341",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [beidl/prime-indicator] Is project dead? (#28)",
"sections": [
{
"text": "",
"activityTitle": "**Alfred E. Neumayer**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@beidl",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"beidl/prime-indicator\",\n\"issueId\": 28,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"beidl/prime-indicator\",\n\"issueId\": 28\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/beidl/prime-indicator/issues/28#issuecomment-403281341"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 354069824\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by fredldotme** [comment]
As mentioned, use one of the maintained forks available. They're shown on a timeline.
