### ISSUE TITLE
Changing multiple times.

### ISSUE THREAD

**Issue by leonpf** [beidl/prime-indicator#5]
Hi, I would like to know if its a bug or I'm doing something wrong with prime-indicator.
My machine
Ubuntu 14.04, 3.13.0-24-generic on a XPS 15 L502X with NVIDIA GeForce GT 540M.
If you need any other information, please tell me.

![menu_001](https://cloud.githubusercontent.com/assets/1045139/2806542/e90ffebc-cccb-11e3-869a-efa05ee161c6.png)

![selection_002](https://cloud.githubusercontent.com/assets/1045139/2806591/36b19076-cccd-11e3-8fcf-8263974d91b6.png)

So, if I try to change one time, works fine. Switch to GeForce from Intel with no problem, but If I want to change back, from Intel to GeForce, I need to reboot the machine.

There's any log file that I can send you, that would help?

Best regards.

**Comment by andrebrait** [comment]
I've just released version 1.0.0 of my fork, which has a ton of bugs fixed as well as some new features and new icons. Check it out: https://github.com/andrebrait/prime-indicator

@rdpascua None. The indicator does just that, but automatically.
