### ISSUE TITLE
Error sh: 1 glxinfo not found Ubuntu 14.04

### ISSUE THREAD

**Issue by deyvisonrocha** [beidl/prime-indicator#6]
After installation on Ubuntu 14.04 and getting erro in appindicator.

**Comment by rhonyabdullah** [comment]
It works ! On my xubuntu 14.04 64bit, thanks

**Comment by unkownY** [comment]
@deyvisonrocha  why did this happened?

**Comment by yaitloutou** [comment]
it works on my ubuntu 16.04, thank you @deyvisonrocha

**Comment by yangmu** [comment]
it works for me. Thanks! @deyvisonrocha

**Comment by fengshh2301** [comment]
It works ! On ubuntu 14.04 64bit
